---
   title: "Factors"  
   author: "Adam Pearce"  
   output:  
     html_document:  
       keep_md: true  
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)

gdURL  <-  "http://tiny.cc/gapminder"
gDat  <- read.delim(file = gdURL)

gtbl <- tbl_df(gDat)
```

Drop Oceania
```{r}
gDat  <- gDat  %>% filter(continent != 'Oceania')
unique(gDat$continent)
dim(gDat)
```

There's still a Oceania level, use `droplevels` to remove
```{r}
gDat  <- gDat  %>% filter(continent != 'Oceania') %>% droplevels
unique(gDat$continent)
dim(gDat)
```

Model life expectancy as a function of the year
```{r}
j_coefs <- ddply(gDat, ~ country + continent, function(dat, offset = 1952) {
  the_fit <- lm(lifeExp ~ I(year - offset), dat)
  setNames(coef(the_fit), c("intercept", "slope"))
})

j_coefs %>% summary
```

arrage sorts smallest to largest, reorder does the opposite.
```{r}
post_arrange <- j_coefs %>% arrange(slope)
head(post_arrange)
tail(post_arrange)

post_reorder <- j_coefs %>%
  mutate(country = reorder(country, slope))
head(post_reorder)
```

Unordered data
```{r}
ggplot(gDat  %>% subset(continent == 'Europe'), aes(x = lifeExp, y = country)) + geom_point(size = 1)
```

Sorting shows the distrubution 
```{r}
ggplot(gDat  %>% subset(continent == 'Europe'), aes(x = lifeExp, y = reorder(country, lifeExp))) + geom_point(size = 1)
```

Save filtered data for later use
```{r}
write.table(gDat, "hDat.csv", sep = ",", row.names = FALSE)
```

